const {EmbedBuilder}=require('discord.js');
const POS=['QB','RB','WR','TE','K','DEF'];
function slugName(u){return`roster-${u.display_name.toLowerCase().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'')}`}
function pline(id,pl){const p=pl[id];if(!p)return`• Unknown (${id})`;return`• **${p.position||'?'}** ${p.first_name} ${p.last_name}${p.team?` — ${p.team}`:''}`}
function sortPos(l,pl){return[...l].sort((a,b)=>(POS.indexOf(pl[a]?.position||'ZZ'))-(POS.indexOf(pl[b]?.position||'ZZ')))}
function chunk(a,n){const o=[];for(let i=0;i<a.length;i+=n)o.push(a.slice(i,i+n));return o}
function formatRosterEmbed(roster,user,players){const s=sortPos(roster.players||[],players);const e=new EmbedBuilder().setTitle(`📋 ${user.display_name} — Full Roster`).setColor(0x5865F2).setDescription('Current roster synced from Sleeper. Updates automatically after every trade, add, or drop.').setTimestamp().setFooter({text:'Doug Da Dynasty Bot • Roster Tracker'});if(!s.length){e.addFields({name:'Players',value:'No players yet — will populate after the draft.',inline:false})}else{chunk(s.map(id=>pline(id,players)),20).forEach((c,i)=>e.addFields({name:i===0?`Players (${s.length})`:'\u200b',value:c.join('\n'),inline:false}))}return e}
function formatRosterDiff(user,added,dropped,players){const e=new EmbedBuilder().setTitle(`📝 Roster Move — ${user.display_name}`).setColor(added.length>dropped.length?0x57F287:dropped.length>added.length?0xED4245:0x5865F2).setTimestamp().setFooter({text:'Doug Da Dynasty Bot • Roster Tracker'});if(added.length)e.addFields({name:'✅ Added',value:added.map(id=>pline(id,players)).join('\n'),inline:true});if(dropped.length)e.addFields({name:'❌ Dropped',value:dropped.map(id=>pline(id,players)).join('\n'),inline:true});return e}
function formatTradeEmbed(trade,rum,players){const e=new EmbedBuilder().setTitle('🔄 Trade Alert').setColor(0xFFA500).setTimestamp(trade.status_updated).setFooter({text:'Doug Da Dynasty Bot • React to weigh in on this trade'});const adds=trade.adds||{},drops=trade.drops||{};const ids=[...new Set([...Object.values(adds),...Object.values(drops)])];for(const rid of ids){const u=rum[rid]||{display_name:`Team ${rid}`};const recv=Object.entries(adds).filter(([,r])=>String(r)===String(rid)).map(([id])=>pline(id,players));const gave=Object.entries(drops).filter(([,r])=>String(r)===String(rid)).map(([id])=>pline(id,players));let s='';if(recv.length)s+=`**Receives:**\n${recv.join('\n')}\n`;if(gave.length)s+=`\n**Gives up:**\n${gave.join('\n')}`;const picks=(trade.draft_picks||[]).filter(p=>String(p.previous_owner_id)===String(rid)||String(p.owner_id)===String(rid));if(picks.length)s+=`\n**Picks:** ${picks.map(p=>`${String(p.owner_id)===String(rid)?'Gets':'Gives'}: ${p.season} Rd ${p.round}`).join(', ')}`;if(trade.waiver_budget?.length){const m=trade.waiver_budget.filter(b=>String(b.receiver)===String(rid));if(m.length)s+=`\n💵 Receives $${m[0].amount} FAAB`}e.addFields({name:`🏈 ${u.display_name}`,value:s||'No players',inline:true})}return e}
function formatStandingsEmbed(rosters,userMap,matchups,nextMatchups,week){const teams=rosters.map(r=>{const u=userMap[r.owner_id]||{display_name:`Team ${r.roster_id}`};const pf=(r.settings.fpts||0)+(r.settings.fpts_decimal||0)/100;return{rosterId:r.roster_id,name:u.display_name,wins:r.settings.wins||0,losses:r.settings.losses||0,ties:r.settings.ties||0,pf}}).sort((a,b)=>b.wins-a.wins||b.pf-a.pf);
let topScorer=null,topScore=0;if(matchups?.length){const sm={};matchups.forEach(m=>{sm[m.roster_id]=(sm[m.roster_id]||0)+(m.points||0)});Object.entries(sm).forEach(([rid,pts])=>{if(pts>topScore){topScore=pts;topScorer=parseInt(rid)}})}
const topName=topScorer?(teams.find(t=>t.rosterId===topScorer)?.name||`Team ${topScorer}`):null;
const medals=['🥇','🥈','🥉'];const sLines=teams.map((t,i)=>`${medals[i]||`${i+1}.`} **${t.name}** — ${t.wins}-${t.losses}${t.ties?`-${t.ties}`:''} | PF: ${t.pf.toFixed(1)}`);
let mLines=[];if(nextMatchups?.length){const p={};nextMatchups.forEach(m=>{if(!p[m.matchup_id])p[m.matchup_id]=[];p[m.matchup_id].push(m)});Object.values(p).forEach(pair=>{if(pair.length===2){const a=teams.find(t=>t.rosterId===pair[0].roster_id)?.name||`Team ${pair[0].roster_id}`;const b=teams.find(t=>t.rosterId===pair[1].roster_id)?.name||`Team ${pair[1].roster_id}`;mLines.push(`• ${a} vs. ${b}`)}})}
const e=new EmbedBuilder().setTitle(`📰 The Dynasty Dispatch — Week ${week} Report`).setColor(0x2C3E50).setTimestamp().setFooter({text:'Doug Da Dynasty Bot • Every Tuesday 9 AM ET'});
if(topName)e.addFields({name:`🏆 High Scorer — Week ${week}`,value:`**${topName}** led the league with **${topScore.toFixed(1)} points** this week.`,inline:false});
e.addFields({name:`📊 Standings After Week ${week}`,value:sLines.join('\n')||'Season has not started yet.',inline:false});
if(mLines.length)e.addFields({name:`🔭 Week ${week+1} Matchup Preview`,value:mLines.join('\n'),inline:false});
e.addFields({name:'💥 Draft Pick Standings',value:'Max PF tracker updated in #max-points-tracker — see where your rookie pick stands.',inline:false});
return e}
function formatMaxPFEmbed(rosters,userMap,week){const teams=rosters.map(r=>{const u=userMap[r.owner_id]||{display_name:`Team ${r.roster_id}`};const m=(r.settings.ppts||0)+(r.settings.ppts_decimal||0)/100;return{name:u.display_name,maxPF:m}}).sort((a,b)=>b.maxPF-a.maxPF);const top=teams[0]?.maxPF||1;const lines=teams.map((t,i)=>{const f=Math.round((t.maxPF/top)*12);const bar='█'.repeat(f)+'░'.repeat(12-f);const note=i===0?' ← holds 1.01':i===teams.length-1?' ← holds last pick':'';return`**${i+1}.** ${t.name}\n\`${bar}\` ${t.maxPF.toFixed(1)} pts${note}`});return new EmbedBuilder().setTitle(`💥 Max Points For Standings — Through Week ${week}`).setColor(0x1ABC9C).setDescription('**This determines rookie draft order for non-playoff teams.**\n\nMax PF = the highest possible score your roster could have earned each week with optimal starting decisions. The team with the **lowest** Max PF earns the 1.01. Tanking your lineup does not help — only genuine roster weakness matters.\n\n'+lines.join('\n\n')).setTimestamp().setFooter({text:'Doug Da Dynasty Bot • Updates every Tuesday 9 AM ET'})}
module.exports={slugName,formatRosterEmbed,formatRosterDiff,formatTradeEmbed,formatStandingsEmbed,formatMaxPFEmbed};
