const {EmbedBuilder}=require('discord.js');
const VOTES=[
{title:'💰 VOTE: Prize Payout Structure',color:0xF1C40F,reactions:['🅰️','🅱️'],fields:[{name:'📖 What Are We Deciding?',value:'The league pot is **$1,200 total** (12 x $100). We need to vote on how it gets paid out at the end of the season.'},{name:'🅰️ Option A — Spread the Wealth',value:'🥇 1st Place: **$700** (58%)\n🥈 2nd Place: **$300** (25%)\n🥉 3rd Place: **$150** (12.5%)\n🏆 Regular Season Points Leader: **$50** (4.5%)\n\nRewards three playoff finishers plus the top regular season scorer.'},{name:'🅱️ Option B — Winner Takes Most',value:'🥇 1st Place: **$800** (67%)\n🥈 2nd Place: **$300** (25%)\n🏆 Regular Season Points Leader: **$100** (8%)\n\nHeavier reward for the champion. Points leader prize is doubled.'},{name:'⚖️ Key Differences',value:'Option A pays out 3rd place ($150) — rewards making the final weekend\nOption B removes 3rd place but doubles the points leader prize\nBoth pay 2nd place the same ($300)'}],footer:'React 🅰️ for Option A  |  🅱️ for Option B'},
{title:'📊 VOTE: League Median Scoring',color:0x3498DB,reactions:['✅','❌'],fields:[{name:'📖 What Is It?',value:'League Median adds a second result every week alongside your head-to-head matchup. Sleeper calculates the median score across all 12 teams. Score above it and you earn a bonus win. Score below and you earn a bonus loss.'},{name:'📊 Real Example',value:'Week 3 median is 112 pts.\n\nScore 128 and WIN matchup — 2-0 for the week\nScore 128 and LOSE matchup — 1-1 because you beat the median\nScore 98 and WIN matchup — 1-1 because you fell below median\nScore 98 and LOSE matchup — 0-2'},{name:'⚖️ Why It Matters',value:'Eliminates the frustration of scoring well and losing because you faced the one team that went off. Rewards consistency and reduces pure schedule luck.'},{name:'✅ Vote YES if...',value:'You want a fairer season where consistent scoring is rewarded regardless of matchup luck.'},{name:'❌ Vote NO if...',value:'You prefer pure head-to-head and believe schedule variance is part of the competition.'}],footer:'React ✅ YES  |  ❌ NO'},
{title:'🔃 VOTE: 3rd Round Reversal (Rookie Draft)',color:0x9B59B6,reactions:['✅','❌'],fields:[{name:'📖 What Is It?',value:'Rounds 1 and 2 go worst-to-first as normal. Round 3 reverses — best record picks first, worst picks last. Rounds 4 and beyond return to standard order.'},{name:'📊 Real Example',value:'Team A finishes 2-12 (worst). Team L finishes 11-3 (best).\n\nRound 1: Team A picks 1st, Team L picks 12th\nRound 2: Team A picks 1st, Team L picks 12th\nRound 3 REVERSED: Team L picks 1st, Team A picks 12th\nRound 4+: Team A picks 1st again'},{name:'⚖️ Why It Matters',value:'Without this the worst team gets picks 1.01, 2.01, AND 3.01 — three top rookies in one draft. That concentration in a rebuild can produce a dominant team for 5+ years. The reversal breaks it up while still giving the worst team the two most valuable picks.'},{name:'✅ Vote YES if...',value:'You want to protect long-term parity and prevent any rebuild from hoarding too much rookie talent.'},{name:'❌ Vote NO if...',value:'You believe the worst team deserves all top picks in every round.'}],footer:'React ✅ YES  |  ❌ NO'},
{title:'🏆 VOTE: Toilet Bowl (Loser Bracket)',color:0xF39C12,reactions:['✅','❌'],fields:[{name:'📖 What Is It?',value:'While the top 6 teams compete in the championship bracket during Weeks 15-17, the bottom 6 teams play a Toilet Bowl bracket at the same time. Real bracket, real stakes — just for the teams that missed the cut.'},{name:'📋 Structure',value:'• Bottom 6 teams seeded 7th-12th by record\n• 3-week bracket runs Weeks 15-17\n• Toilet Bowl winner: +$15 FAAB added to next season budget\n• Toilet Bowl loser: Bragging rights only — no penalty'},{name:'📊 How Max PF Determines Everything',value:'Draft order and standings for ALL non-playoff teams are determined entirely by Max PF — the highest possible score your roster could have earned each week with optimal lineup decisions.\n\n• Lowest Max PF earns the 1.01 pick\n• Highest Max PF among non-playoff teams picks last\n• This applies regardless of Toilet Bowl result\n• Tanking your lineup does not help — only genuine roster weakness earns a top pick'},{name:'🎯 Why This Works',value:'The Toilet Bowl keeps all 12 managers setting lineups through the final week. The $15 FAAB bonus gives the winner something real to play for. But because draft order is Max PF based no one has any reason to lose on purpose — ever.'},{name:'✅ Vote YES if...',value:'You want a loser bracket that keeps everyone engaged with a small FAAB reward for the winner and zero impact on draft order.'},{name:'❌ Vote NO if...',value:'You prefer playoffs to only involve the top 6 teams.'}],footer:'React ✅ YES  |  ❌ NO'},
{title:'📅 VOTE: Official Offseason Calendar',color:0x1ABC9C,reactions:['✅','❌'],fields:[{name:'📖 What Is It?',value:'A fixed calendar every manager knows in advance — no confusion about when trades open, when the draft is, or when dues are due.'},{name:'📆 Proposed Calendar',value:'• Feb 1-15: Trade window opens — future picks only\n• Mar 1: Draft order locked by Max PF standings\n• May 1: Rookie draft held\n• Jul 1: Full trade window reopens — players and picks\n• Aug 1: Dues deadline\n• Aug 15: Rosters locked, IR set\n• Sep 1: Season begins'},{name:'💡 What You Always Know',value:'Exactly when you can trade players, when the draft is, when dues are due, and when rosters lock. No surprises, no last minute scrambles.'},{name:'✅ Vote YES if...',value:'You want a predictable structured offseason where every manager knows what is coming.'},{name:'❌ Vote NO if...',value:'You prefer the commissioner to set dates year by year.'}],footer:'React ✅ YES  |  ❌ NO'}
];
async function postVotes(ch){
  const hdr=new EmbedBuilder().setTitle('⚙️ League Settings & Voting').setColor(0x2C3E50).setDescription('This is where league settings, rule proposals, and payout options are voted on.\n\nRead each proposal carefully. A majority vote (7 of 12) is required to adopt any rule. Results reviewed by the commissioner.\n\nManaged by Doug Da Dynasty Bot').setTimestamp().setFooter({text:'Doug Da Dynasty Bot • League Settings'});
  await ch.send({embeds:[hdr]});
  for(const v of VOTES){
    const e=new EmbedBuilder().setTitle(v.title).setColor(v.color).setFooter({text:v.footer}).setTimestamp();
    v.fields.forEach(f=>e.addFields({name:f.name,value:f.value,inline:false}));
    const msg=await ch.send({embeds:[e]});
    for(const r of v.reactions)await msg.react(r).catch(()=>{});
    await new Promise(r=>setTimeout(r,1000));
  }
}
module.exports={postVotes};
